<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE mods [
    <!ELEMENT mods (mod*)>
    <!ATTLIST mods format         CDATA #REQUIRED
                   name           CDATA "ModsParam.xml"
                   description    CDATA "CM3D2.AddModsSlider.Plugin の各modスライダーのパラメータ定義用XML">
    <!ELEMENT mod (value*)>
    <!ATTLIST mod id              CDATA #REQUIRED
                  description     CDATA ""
                  enabled         CDATA "false"
                  type            CDATA "slider">
    <!ELEMENT value EMPTY>
    <!ATTLIST value prop_name     CDATA #REQUIRED
                    min           CDATA "0"
                    max           CDATA "10"
                    label         CDATA ""
                    type          CDATA "num"
                    match_pattern CDATA "([-+]?[0-9]*\.?[0-9]+)">
] >

<!--
    設置場所 : \CM3D2\UnityInjector\Config\ModsParam.xml

    書式説明 : CM3D2.AddModsSlider.Plugin.0.0.4.5 に対応

    <mod id="EYEBALL"                    : 必須。modの識別名。拡張セーブデータを参照。
         description="..."               : 省略可。規定値は空白。modの説明。
         type="slider"                   : 省略可。規定値は"slider"。"toggle"で<value />タグ不要のトグルボタンに。
    >
    
        <value prop_name="EYEBALL.width" : 必須。valueの識別名。拡張セーブデータを参照。
               min="0.1"                 : 省略可。規定値は"0"。スライダーの最小値。
               max="2.0"                 : 省略可。規定値は"10"。スライダーの最大値。
               label="横"                : 省略可。規定値は空白。スライダーのラベル。
               type="scale"              : 省略可。規定値は"num"。「倍率」なら"scale"。「整数値」なら"int"。
               match_pattern="..."       : 省略可。規定値は"([-+]?[0-9]*\.?[0-9]+)"。valueの正規表現マッチパターン。
         />

        <value prop_name="EYEBALL.height" min="0.1" max="2.0" label="縦" type="scale" />
                                         : <value ... /> の一行表記。

        ...                              : modが必要とする入力数値分だけ、 <value ... /> を記載する。
    </mod>
-->


<mods format="1.1" name="ModsParam.xml"
      description="CM3D2.AddModsSlider.Plugin の各modスライダーのパラメータ定義用XML">

<!-- Stable -->
    <mod id="WIDESLIDER" description ="Unlock silders" type="toggle" />
    <mod id="PROPSET_OFF" description ="Disable @PropSet in yotogi" type="toggle" />
    <mod id="HYOUJOU_OFF" description ="Disable facial expressions" type="toggle" />
    <mod id="MUHYOU" description ="Lock face (no expressions, lipsync, etc)" type="toggle" />

    <mod id="PITCH" description ="Voice modification">
        <value prop_name="PITCH.value" min="-0.5" max="0.5" default="0" label="Pitch" type="num" />
    </mod>

    <mod id="MABATAKI" description ="Eyelid Modification">
        <value prop_name="MABATAKI.value" min="0" max="1.0" default="0" label="Angle" type="num" />
    </mod>

    <mod id="TEST_MABATAKI_SPEED" description ="Blinking speed">
        <value prop_name="MABATAKI.value" min="0" max="2.0" default="1.0" label="Value" type="num" />
    </mod>

    <mod id="EYEBALL" description="Iris Scaling">
        <value prop_name="EYEBALL.width" min="0.1" max="2.0" default="1.0" label="Width" type="scale" />
        <value prop_name="EYEBALL.height" min="0.1" max="2.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="TEST_EYE_RATIO" description="[TEST] Eye Ratio">
        <value prop_name="EYE_RATIO.value" min="0.1" max="2.0" default="1.0" label="Ratio" type="scale" />
    </mod>

    <mod id="TEST_EYE_ANG" description="[TEST] Eye Modification">
        <value prop_name="EYE_ANG.angle" min="-60" max="60" default="0" label="Angle"  type="num" />
        <value prop_name="EYE_ANG.x" min="-100" max="100" default="0" label="Vertical Position"  type="num" />
        <value prop_name="EYE_ANG.y" min="-100" max="100" default="0" label="Eye Distance"  type="num" />
    </mod>

    <mod id="TEST_PELSCL" description="[TEST] Pelvis Scaling">
        <value prop_name="PELSCL.width" min="0.1" max="2.0" default="1.0" label="Width" type="scale" />
        <value prop_name="PELSCL.depth" min="0.1" max="2.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="PELSCL.height" min="0.1" max="2.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="TEST_PELVIS" description="[TEST] Skirt Collision">
        <value prop_name="PELVIS.x" min="-2.0" max="10.0" default="1.0" label="Value 1" type="num" />
        <value prop_name="PELVIS.y" min="-2.0" max="10.0" default="1.0" label="Value 2" type="num" />
        <value prop_name="PELVIS.z" min="-2.0" max="10.0" default="1.0" label="Value 3" type="num" />
    </mod>

    <mod id="TEST_THISCL" description="[TEST] Leg Scaling">
        <value prop_name="THISCL.width" min="0.5" max="2.0" default="1.0" label="Width" type="scale" />
        <value prop_name="THISCL.depth" min="0.5" max="2.0" default="1.0" label="Depth" type="scale" />
    </mod>

    <mod id="TEST_THIPOS" description="[TEST] Leg Position">
        <value prop_name="THIPOS.x" min="-50" max="0" default="0" label="L / R" type="num" />
        <value prop_name="THIPOS.z" min="-50" max="50" default="0" label="F / B" type="num" />
    </mod>
</mods>