<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE mods [
    <!ELEMENT mods (mod*)>
    <!ATTLIST mods format         CDATA #REQUIRED
                   name           CDATA "ModsParam.xml"
                   description    CDATA "CM3D2.AddModsSlider.Plugin の各modスライダーのパラメータ定義用XML">
    <!ELEMENT mod (value*)>
    <!ATTLIST mod id              CDATA #REQUIRED
                  description     CDATA ""
                  type            CDATA "slider"
                  on_wideslider   CDATA "false"
                  visible         CDATA "true">
    <!ELEMENT value EMPTY>
    <!ATTLIST value prop_name     CDATA #REQUIRED
                    min           CDATA "0"
                    max           CDATA "10"
                    label         CDATA ""
                    type          CDATA "num"
                    default       CDATA "NaN"
                    visible       CDATA "true">
] >

<!--
    設置場所 : \CM3D2\UnityInjector\Config\ModsParam.xml

    書式説明 : CM3D2.AddModsSlider.Plugin.0.1.2.17 以降に対応

    <mod id="EYEBALL"                    : 必須。modの識別名。拡張セーブデータを参照。
         description="..."               : 省略可。規定値は空白。modの説明。
         type="slider"                   : 省略可。規定値は"slider"。"toggle"でOn/Offボタン(<value />タグ不要)、"toggle,slider"でOn/Offボタン付きスライダー。
         on_wideslider="false"           : 省略可。規定値は"false"。"true"指定するとWIDESLIDER無効時に非表示になる。WIDESLIDER前提のmod用。
         visible="true"                  : 省略可。規定値は"true"。"false"指定でこのmodのスライダーを表示させない。
    >
    
        <value prop_name="EYEBALL.width" : 必須。valueの識別名。拡張セーブデータを参照。
               min="0.1"                 : 省略可。規定値は"0"。スライダーの最小値。
               max="2.0"                 : 省略可。規定値は"10"。スライダーの最大値。
               label="横"                : 省略可。規定値は空白。スライダーのラベル。
               type="scale"              : 省略可。規定値は"num"。「倍率」なら"scale"。「整数値」なら"int"。
               default="1.0"             : 省略可。規定値は"NaN"。valueの初期値。(省略時はtype="num"or"int"の時は"0"、type="scale"の時は"1"として扱う)。
               visible="true"            : 省略可。規定値は"true"。"false"指定でこのvalueのスライダーを表示させない。
        />

        <value prop_name="EYEBALL.height" min="0.1" max="2.0" label="縦" type="scale" />
                                         : <value ... /> の一行表記。

        ...                              : modが必要とする入力数値分だけ、 <value ... /> を記載する。
    </mod>
-->


<mods format="1.21" name="ModsParam.xml"
      description="CM3D2.AddModsSlider.Plugin の各modスライダーのパラメータ定義用XML">

    <mod id="WIDESLIDER" description ="Unlock sliders" type="toggle" />
    <mod id="PROPSET_OFF" description ="@PropSet fix" type="toggle" />
    <mod id="LIPSYNC_OFF" description ="Disable lip-sync" type="toggle" />
    <mod id="HYOUJOU_OFF" description ="Lock facial expression" type="toggle" />
    <mod id="EYETOCAMERA_OFF" description ="Disable @EyeToCamera script command" type="toggle" />
    <mod id="MUHYOU" description ="Disable all face animations" type="toggle" />
    <mod id="FARMFIX" description ="Forearm distortion fix" on_wideslider="true" type="toggle" />
    <mod id="FACE_OFF" description ="Disable @Face script command" type="toggle" />
    <mod id="FACEBLEND_OFF" description ="Disable @FaceBlend script command" type="toggle" />

    <mod id="EYETOCAM" description ="EyeToCam mode" >
        <value prop_name="EYETOCAM" min="-1" max="1" label="Value" type="int" />
    </mod>
    
    <mod id="HEADTOCAM" description ="HeadToCam mode" >
        <value prop_name="HEADTOCAM" min="-1" max="1" label="Value" type="int" />
    </mod>

    <mod id="PITCH" description ="Voice pitch" >
        <value prop_name="PITCH" min="-0.5" max="0.5" default="0" label="Value" type="num" />
    </mod>

    <mod id="MABATAKI" description ="Eye-lid open angle" >
        <value prop_name="MABATAKI" min="0" max="1.0" default="1.0" label="Value" type="num" />
    </mod>

    <mod id="LIPSYNC_INTENISTY" description="Lip-sync intensity" type="toggle,slider" >
        <value prop_name="LIPSYNC_INTENISTY.value" min="0.0" max="1.0" default="1.0" label="Value" type="num" />
    </mod>

    <mod id="EYEBALL" description="Iris scaling" >
        <value prop_name="EYEBALL.width" min="0.1" max="2.0" default="1.0" label="Width" type="scale" />
        <value prop_name="EYEBALL.height" min="0.1" max="2.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="EYE_ANG" description="Eye angle" on_wideslider="true" >
        <value prop_name="EYE_ANG.angle" min="-60"  max="60"  default="0" label="Angle" type="num" />
        <value prop_name="EYE_ANG.x"     min="-200" max="200" default="0" label="Horizontal correction" type="num" />
        <value prop_name="EYE_ANG.y"     min="-200" max="200" default="0" label="Vertical correction" type="num" />
    </mod>

    <mod id="PELSCL" description="Pelvis scaling" on_wideslider="true" >
        <value prop_name="PELSCL.width"  min="0.1" max="2.0" default="1.0" label="Width" type="scale" />
        <value prop_name="PELSCL.depth"  min="0.1" max="2.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="PELSCL.height" min="0.1" max="2.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="THIPOS" description="Leg position" on_wideslider="true" >
        <value prop_name="THIPOS.x" min="-100" max="200" default="0.0" label="Left / Right" type="num" />
        <value prop_name="THIPOS.y" min="-100" max="200" default="0.0" label="Up / Down" type="num" visible="false" />
        <value prop_name="THIPOS.z" min="-100" max="200" default="0.0" label="Front / Back" type="num" />
    </mod>

    <mod id="THISCL" description="Leg scaling"  on_wideslider="true" >
        <value prop_name="THISCL.width" min="0.1" max="2.0" default="1.0" label="Width" type="scale" />
        <value prop_name="THISCL.depth" min="0.1" max="2.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="THISCL.height" min="0.1" max="2.0" default="1.0" label="Height" type="scale" visible="false" />
    </mod>

    <mod id="THISCL2" description="Knee scaling"  on_wideslider="true" >
        <value prop_name="THISCL2.width" min="0.1" max="2.0" default="1.0" label="Width" type="scale" />
        <value prop_name="THISCL2.depth" min="0.1" max="2.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="THISCL2.height" min="0.1" max="2.0" default="1.0" label="Height" type="scale" visible="false" />
    </mod>

    <mod id="CALFSCL" description="Calf scaling"  on_wideslider="true" >
        <value prop_name="CALFSCL.width" min="0.1" max="2.0" default="1.0" label="Width" type="scale" />
        <value prop_name="CALFSCL.depth" min="0.1" max="2.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="CALFSCL.height" min="0.1" max="2.0" default="1.0" label="Height" type="scale" visible="false" />
    </mod>

    <mod id="SKTSCL" description="Skirt collision scaling" on_wideslider="true">
        <value prop_name="SKTSCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="SKTSCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="SKTSCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="SKTPOS" description="Skirt position"  on_wideslider="true" >
        <value prop_name="SKTPOS.x" min="-1" max="1" default="0.0" label="Left / Right" type="num" visible="false" />
        <value prop_name="SKTPOS.y" min="-1" max="1" default="0.0" label="Front / Back" type="num" visible="false" />
        <value prop_name="SKTPOS.z" min="-1" max="1" default="0.0" label="Up / Down" type="num" />
    </mod>

    <mod id="SPISCL" description="Lower abdomen scaling" on_wideslider="true">
        <value prop_name="SPISCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="SPISCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="SPISCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="S0ASCL" description="Abdomen scaling" on_wideslider="true">
        <value prop_name="S0ASCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="S0ASCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="S0ASCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="S1_SCL" description="Stomach scaling" on_wideslider="true">
        <value prop_name="S1_SCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="S1_SCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="S1_SCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="S1ASCL" description="Chest scaling" on_wideslider="true">
        <value prop_name="S1ASCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="S1ASCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="S1ASCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="S1ABASESCL" description="Upper torso scaling" on_wideslider="true">
        <value prop_name="S1ABASESCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="S1ABASESCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="S1ABASESCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" visible="false" />
    </mod>

    <mod id="MUNESCL" description="Breast scaling" on_wideslider="true">
        <value prop_name="MUNESCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="MUNESCL.depth"  min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
        <value prop_name="MUNESCL.height" min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
    </mod>

    <mod id="MUNEPOS" description="Breast position" on_wideslider="true">
        <value prop_name="MUNEPOS.x" min="-1" max="1" default="0" label="Left / Right" type="num" />
        <value prop_name="MUNEPOS.z" min="-1" max="1" default="0" label="Up / Down" type="num" />
        <value prop_name="MUNEPOS.y" min="-1" max="1" default="0" label="Front / Back" type="num" />
    </mod>

    <mod id="MUNESUBSCL" description="Breast sub scaling" on_wideslider="true">
        <value prop_name="MUNESUBSCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="MUNESUBSCL.depth"  min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
        <value prop_name="MUNESUBSCL.height" min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
    </mod>

    <mod id="MUNESUBPOS" description="Breast sub position" on_wideslider="true">
        <value prop_name="MUNESUBPOS.x" min="-1" max="1" default="0" label="Left / Right" type="num" />
        <value prop_name="MUNESUBPOS.z" min="-1" max="1" default="0" label="Up / Down" type="num" />
        <value prop_name="MUNESUBPOS.y" min="-1" max="1" default="0" label="Front / Back" type="num" />
    </mod>

    <mod id="NECKSCL" description="Neck scaling" on_wideslider="true">
        <value prop_name="NECKSCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="NECKSCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="NECKSCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="KATASCL" description="Shoulder scaling" on_wideslider="true">
        <value prop_name="KATASCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="KATASCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="KATASCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="UPARMSCL" description="Upper arm scaling" on_wideslider="true">
        <value prop_name="UPARMSCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="UPARMSCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="UPARMSCL.height" min="0.1" max="3.0" default="1.0" label="Height" type="scale" />
    </mod>

    <mod id="FARMSCL" description="Forearm scaling" on_wideslider="true">
        <value prop_name="FARMSCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="FARMSCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="FARMSCL.height" min="0.1" max="3.0" default="1.0" label="Length" type="scale" />
    </mod>

    <mod id="HANDSCL" description="Hand scaling" on_wideslider="true">
        <value prop_name="HANDSCL.width"  min="0.1" max="3.0" default="1.0" label="Width" type="scale" />
        <value prop_name="HANDSCL.depth"  min="0.1" max="3.0" default="1.0" label="Depth" type="scale" />
        <value prop_name="HANDSCL.height" min="0.1" max="3.0" default="1.0" label="Length" type="scale" />
    </mod>

    <mod id="HEAD_TRACK" description="Head &amp; eye tracking modification" type="toggle,slider">
        <value prop_name="HEAD_TRACK.lateral" min="0"   max="90"  default="30"   label="[Head] Horizontal angle limit" type="num" />
        <value prop_name="HEAD_TRACK.above"   min="-90" max="90"  default="30"   label="[Head] Upwards angle limit" type="num" />
        <value prop_name="HEAD_TRACK.below"   min="-90" max="90"  default="15"   label="[Head] Downwards angle limit" type="num" />
        <value prop_name="HEAD_TRACK.behind"  min="0"   max="180" default="90"   label="[Head] Tracking reset angle" type="scale" />
        <value prop_name="HEAD_TRACK.speed"   min="0"   max="1.0" default="0.04" label="[Head] Tracking speed" type="num" />
        <value prop_name="HEAD_TRACK.ofsx"    min="-90" max="90"  default="0"    label="[Head] Horizontal offset" type="num" />
        <value prop_name="HEAD_TRACK.ofsy"    min="-90" max="90"  default="0"    label="[Head] Vertical offset" type="num" />
        <value prop_name="HEAD_TRACK.ofsz"    min="-90" max="90"  default="0"    label="[Head] Rotation offset" type="num" />

        <value prop_name="EYE_TRACK.inside"   min="0"   max="90"  default="35"   label="[Eyes] Inner angle limit" type="num" />
        <value prop_name="EYE_TRACK.outside"  min="0"   max="90"  default="65"   label="[Eyes] Outer angle limit" type="num" />
        <value prop_name="EYE_TRACK.above"    min="-90" max="90"  default="10"   label="[Eyes] Upwards angle limit" type="num" />
        <value prop_name="EYE_TRACK.below"    min="-90" max="90"  default="20"   label="[Eyes] Downwards angle limit" type="num" />
        <value prop_name="EYE_TRACK.behind"   min="0"   max="180" default="0.04" label="[Eyes] Tracking reset angle" type="scale" />
        <value prop_name="EYE_TRACK.speed"    min="0"   max="1.0" default="0.07" label="[Eyes] Tracking speed" type="num" />
        <value prop_name="EYE_TRACK.ofsx"     min="-90" max="90"  default="0"    label="[Eyes] Horizontal offset" type="num" />
        <value prop_name="EYE_TRACK.ofsy"     min="-90" max="90"  default="0"    label="[Eyes] Vertical offset" type="num" />
    </mod>

</mods>
